[2024-11-24T03:03:38.790+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.load_to_mysql manual__2024-11-24T03:03:34.650850+00:00 [queued]>
[2024-11-24T03:03:38.796+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.load_to_mysql manual__2024-11-24T03:03:34.650850+00:00 [queued]>
[2024-11-24T03:03:38.797+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-11-24T03:03:38.808+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): load_to_mysql> on 2024-11-24 03:03:34.650850+00:00
[2024-11-24T03:03:38.818+0000] {standard_task_runner.py:57} INFO - Started process 92 to run task
[2024-11-24T03:03:38.820+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_reddit_pipeline', 'load_to_mysql', 'manual__2024-11-24T03:03:34.650850+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmp8n2m0bsy']
[2024-11-24T03:03:38.823+0000] {standard_task_runner.py:85} INFO - Job 7: Subtask load_to_mysql
[2024-11-24T03:03:38.858+0000] {task_command.py:415} INFO - Running <TaskInstance: etl_reddit_pipeline.load_to_mysql manual__2024-11-24T03:03:34.650850+00:00 [running]> on host ed5257f0374c
[2024-11-24T03:03:38.912+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Yusuf Ganiyu' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='load_to_mysql' AIRFLOW_CTX_EXECUTION_DATE='2024-11-24T03:03:34.650850+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-24T03:03:34.650850+00:00'
[2024-11-24T03:03:39.981+0000] {logging_mixin.py:151} INFO - Error connecting to MySQL: 2005 (HY000): Unknown MySQL server host 'your_mysql_host' (-5)
[2024-11-24T03:03:39.981+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/mysql_pipeline.py", line 19, in load_data_to_mysql
    create_table_if_not_exist(connection, table_name)
  File "/opt/airflow/etls/mysql_etl.py", line 21, in create_table_if_not_exist
    cursor = connection.cursor()
AttributeError: 'NoneType' object has no attribute 'cursor'
[2024-11-24T03:03:39.990+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=etl_reddit_pipeline, task_id=load_to_mysql, execution_date=20241124T030334, start_date=20241124T030338, end_date=20241124T030339
[2024-11-24T03:03:39.999+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 7 for task load_to_mysql ('NoneType' object has no attribute 'cursor'; 92)
[2024-11-24T03:03:40.037+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-11-24T03:03:40.049+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
