[2024-11-24T02:54:01.331+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.load_to_mysql scheduled__2024-11-23T00:00:00+00:00 [queued]>
[2024-11-24T02:54:01.338+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.load_to_mysql scheduled__2024-11-23T00:00:00+00:00 [queued]>
[2024-11-24T02:54:01.339+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-11-24T02:54:01.351+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): load_to_mysql> on 2024-11-23 00:00:00+00:00
[2024-11-24T02:54:01.356+0000] {standard_task_runner.py:57} INFO - Started process 80 to run task
[2024-11-24T02:54:01.359+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_reddit_pipeline', 'load_to_mysql', 'scheduled__2024-11-23T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmpfpnyvqnh']
[2024-11-24T02:54:01.362+0000] {standard_task_runner.py:85} INFO - Job 5: Subtask load_to_mysql
[2024-11-24T02:54:01.402+0000] {task_command.py:415} INFO - Running <TaskInstance: etl_reddit_pipeline.load_to_mysql scheduled__2024-11-23T00:00:00+00:00 [running]> on host ed5257f0374c
[2024-11-24T02:54:01.458+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Yusuf Ganiyu' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='load_to_mysql' AIRFLOW_CTX_EXECUTION_DATE='2024-11-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-23T00:00:00+00:00'
[2024-11-24T02:54:02.486+0000] {logging_mixin.py:151} INFO - Error connecting to MySQL: 2005 (HY000): Unknown MySQL server host 'your_mysql_host' (-5)
[2024-11-24T02:54:02.487+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/mysql_pipeline.py", line 19, in load_data_to_mysql
    create_table_if_not_exist(connection, table_name)
  File "/opt/airflow/etls/mysql_etl.py", line 21, in create_table_if_not_exist
    cursor = connection.cursor()
AttributeError: 'NoneType' object has no attribute 'cursor'
[2024-11-24T02:54:02.496+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=etl_reddit_pipeline, task_id=load_to_mysql, execution_date=20241123T000000, start_date=20241124T025401, end_date=20241124T025402
[2024-11-24T02:54:02.510+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 5 for task load_to_mysql ('NoneType' object has no attribute 'cursor'; 80)
[2024-11-24T02:54:02.534+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-11-24T02:54:02.546+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
